In [5]:
x = 7

In [6]:
y = 2.5

In [7]:
type(x)

int

In [8]:
type(y)

float

In [9]:
x + y

9.5

In [10]:
total = x + y

In [11]:
s = "7"

In [12]:
type(s)

str

In [13]:
7 + "7"

TypeError: ignored

In [14]:
7 + int("7")

14

In [15]:
7 + float("7")

14.0

In [16]:
str(7) + "7" + "apple"

'77apple'

In [17]:
# Tax and Tip Cal

In [19]:
check = input("How much is your meal? ")
check = float(check)
tax_rate = 0.08
tip_rate = 0.2

tax = check * tax_rate
tip = check * tip_rate
total = check + tax + tip
print("Your total is",total)

How much is your meal? 100
Your total is 128.0

In [20]:
# Pandas

In [21]:
import pandas as pd

In [22]:
df = pd.DataFrame()

In [23]:
df["Stock"] = ["MSFT", "AAPL", "IBM", "ORCL"]
df["Price"] = [200, 300, 50, 100]

In [29]:
df["Shares"] = [100, 200, 300, 400]
df["Amnt"] = df["Price"] * df["Shares"]
df

  Stock  Price  Shares   Amnt
0  MSFT    200     100  20000
1  AAPL    300     200  60000
2   IBM     50     300  15000
3  ORCL    100     400  40000

In [31]:
condition = df["Price"] < 100
df[condition]

  Stock  Price  Shares   Amnt
2   IBM     50     300  15000

In [33]:
condition_max = df["Amnt"]==df["Amnt"].max()
df[condition_max]

  Stock  Price  Shares   Amnt
1  AAPL    300     200  60000